version: '3.8'

volumes:
  postgres_data:

services:
  postgres:
    image: postgres:18
    restart: no
    environment:
      POSTGRES_DB: lab3db
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    command: ["postgres", "-c", "log_statement=all"]
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init-db.sql
      - postgres_data:/var/lib/postgresql
    entrypoint: ["bash", "-c", "docker-entrypoint.sh postgres"]
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DATABASE_USERNAME} -d lab3db" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  lab3_app:
    build: .
    container_name: lab3_app
    restart: no
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - ./.env
    deploy:
      resources:
        limits:
          cpus: 4
          memory: 4096M
    tmpfs:
      - /tmp # Обязательно для java приложений